// leave off @2x/@3x
const images = {
    bg: require('../Assets/Images/bg.jpg'),
    bg2: require('../Assets/Images/bg2.jpg'),
    iland: require('../Assets/Images/iland.jpg'),
    pineapple: require('../Assets/Images/pineapple.jpg'),
    whale: require('../Assets/Images/whale.jpg'),
    piano_playing: require('../Assets/Images/piano-playing.jpg'),
    user: require('../Assets/Images/user5.jpg'),
    dark_background: require('../Assets/Images/dark-background.jpg'),
    send_icon: require('../Assets/Images/send.png'),
    explore_icon: require('../Assets/Icons/explore.png'),
    feed_icon: require('../Assets/Icons/feed.png'),
    add_icon: require('../Assets/Icons/add.png'),
    chat_icon: require('../Assets/Icons/chat.png'),
    profile_icon: require('../Assets/Icons/profile.png'),
    filter_icon: require('../Assets/Icons/filter.png'),
    map_icon: require('../Assets/Icons/map.png'),
    location_icon: require('../Assets/Icons/location-outline.png'),
    locationFill_icon: require('../Assets/Icons/location.png'),
    share_icon: require('../Assets/Icons/share.png'),
    reset_icon: require('../Assets/Icons/reset.png'),
    currentLocation_icon: require('../Assets/Icons/current-location.png'),
    calender_icon: require('../Assets/Icons/calender.png'),
    user_icon: require('../Assets/Icons/user.png'),
    heartOutline_icon: require('../Assets/Icons/heart-outline.png'),
    check_icon: require('../Assets/Icons/check.png'),
    arrowLeft_icon: require('../Assets/Icons/arrow-left.png'),
    car_icon: require('../Assets/Icons/car.png'),
    bus_icon: require('../Assets/Icons/bus.png'),
    walk_icon: require('../Assets/Icons/walk.png'),
    wifiOff_icon: require('../Assets/Icons/wifi-off.png'),
    arrowReverse_icon: require('../Assets/Icons/arrow-reverse.png'),
    faceId_icon: require('../Assets/Icons/Face-Id.png'),
}

export default images;
